### ISSUE TITLE
"Run without debugging" runs debugger

### ISSUE THREAD

**Issue by AndiMD** [julia-vscode/julia-vscode#1069]
Simple problem: I cannot run my julia script in the REPL anymore. Ctrl+F5 and the corresponding Menu entry "Run without debugging" runs the debugger.

This is a major issue for me: 1) Debugging crashes when trying to plot in Makie and 2) too slow for my kind of work.

Setup:
Clean install of: vscode 1.43.1, Extension Julia 0.15.16
Julia 1.4.0 with a PackageCompiler sysimage including Makie
OS: Linux

**Comment by davidanthoff** [comment]
So Ctrl+F5 should run your script, but _not_ in the debugger. The debugger UI might show up, but it should not be any slower than running the code normally in Julia because Ctrl+F5 goes into a run, not debug mode.

You can also manually configure a new keyboard shortcut for "Run file in REPL" for now, also see https://github.com/julia-vscode/julia-vscode/issues/1070.

If this doesn't help, let me know, but for now I'm closing this issue because I don't think there is anything we need to change.

**Comment by AndiMD** [comment]
Thanks for the quick reply.
I might reopen this once I get around to investigate further. At the moment, running with Ctrl+F5 is way slower than just running each line with Alt+Enter. Also, it crashes with the final message "Julia debuggee finished. Press ENTER to close this terminal".

**Comment by davidanthoff** [comment]
Ctrl+F5 will spin up a new Julia process and run the whole script in there, so that might well be slower than running stuff in an existing REPL where some code might already be compiled etc.

The error message is more concerning, but maybe the simple explanation is that `LibFreeType` is something that is only defined in your REPL process?

**Comment by AndiMD** [comment]
You are correct. 1) The startup time difference is just the REPL spinning up. 2) The error occurs even when running julia from shell. Strangely enough, it does not occur when pasting code into the REPL, anyways this is not related to julia-vscode.
