### ISSUE TITLE
slow debugger and lack of variable tracing 

### ISSUE THREAD

**Issue by YousefSaber** [julia-vscode/julia-vscode#1108]
the debugger is very very slow to start !!

also there is no variable tracing as shown in the following screenshot 
![image](https://user-images.githubusercontent.com/33742499/79143423-84e34800-7dbd-11ea-8512-985aeef40c0b.png)

**Comment by davidanthoff** [comment]
Yes, the debugger is just slow right now. I don't expect that to improve anytime soon, some of this is due to the underlying tech that we use and out of the control of the VS Code extension here.

Variable watch support for global variables is a missing feature that is tracked in https://github.com/julia-vscode/julia-vscode/issues/1046.

I'm closing this issue because all the TODOs to improve the situation are already tracked in other issues.
