### ISSUE TITLE
Add command to stop execution

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1149]
Sometimes I run some commands that on second thought I notice take a huge time to finish. It'd be good if there was a robust way to stop the execution then. Ctrl-c doesn't seem effective, and it usually leads to errors when effective.

**Comment by davidanthoff** [comment]
I agree, having a robust code interruption story would be really nice.

Unfortunately I don't really know how we would do this... Generally we have two execution modes right now: in the first we send code to the REPL as if it was copy pasted. I thinkin that situation Ctrl+C should work in the same way as in the base REPL. The second model is that we run code on a background green thread. I have no idea right now how we might be able to interrupt that stuff...

**Comment by ZacLN** [comment]
Would a command such as:
```typescript
function killREPL() {
    g_terminal.processId.then(pid=>process.kill(pid, 'SIGINT'))
}
```
be usable?

**Comment by marius311** [comment]
I'm sure you're all not lacking things on your todo lists, but if this could be dug out of the backlog, I think it'd be super useful. At the moment its pretty painful to do development on anything that takes more than a few seconds to run, since its just a lot of sitting and waiting if you accidetally launch something you didn't mean to.

**Comment by theogf** [comment]
Making a bump on this issue as it is pretty major in my opinion :)

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1690

**Comment by caseykneale** [comment]
I'll chime in here and say, this is pretty neccesary. For programs involving huge chunks of data, the inability to interrupt means tons of wasted time.

For example, if you are training a model, but have callbacks or some notification saying "hey your weights are all NaNs" or a million messages saying "proposal rejected due to numerical issues", having to reload data, or start over is pretty rough. Especially with TTFP.

**Comment by pfitzseb** [comment]
This is released now.

**Comment by theloni-monk** [comment]
Hey does this feature work for notebooks as well? I haven't been able to halt execution of a notebook cell. As stated above, it would be a useful feature given that misclicks are often huge timesinks currently.

**Comment by pfitzseb** [comment]
It does not, I think.

**Comment by pfitzseb** [comment]
That's a separate issue. https://github.com/julia-vscode/julia-vscode/issues/2039 tracks interrupts for notebooks.
