### ISSUE TITLE
Improve RPC protocol for terminalserver

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1203]
Would be nice if this was a bit less ad-hoc and allow for both messaging and two-way communication.

The callback mechanism Juno uses should work fine here as well.

**Comment by davidanthoff** [comment]
Yes, the current implementation is a mess :)

Do you have a link to the Juno code for this? I'd like to take a look.

I actually think that if we were to combine the variuos bits and pieces that are spread out over the LS, debug and REPL code base, and just picked the best aspect of each, we would also end up with something reasonable :)

I think my gut preference would be that we just adopt JSON-RCP for this, as that is already used on the LS side and we could probably use the same implementation for both. The existing Julia implementation of that on the LS side I think is solid, i.e. it supports request-response type patterns, and notifications, and has things like correlating responses to the right request etc. implemented.

I think right now the implementation also uses two named pipes, which is also silly, we should just use one.

I'll take a quick look later today whether we can just reuse some of the existing code.

**Comment by pfitzseb** [comment]
> I think my gut preference would be that we just adopt JSON-RCP for this

Yeah, agreed. The only question is how to load JSON into the Julia process, but I guess vendoring JSON@0.20 (which doesn't have any deps) should be fine.

> Do you have a link to the Juno code for this? I'd like to take a look.

Not really, no. At least the JS side is a bit hard to understand. The [Julia side](https://github.com/JunoLab/Atom.jl/blob/master/src/comm.jl) is nice though, imho.

**Comment by davidanthoff** [comment]
> The only question is how to load JSON into the Julia process, but I guess vendoring JSON@0.20 (which doesn't have any deps) should be fine.

Agreed.

> At least the JS side is a bit hard to understand.

We could try to just use https://www.npmjs.com/package/vscode-jsonrpc on the TypeScript side?

> The Julia side is nice though, imho.

Yes, I think the callback style API makes a lot of sense. I implemented something like that (but without an API or the elegance of the code you linked to) for the debugger [here](https://github.com/julia-vscode/julia-vscode/blob/4d06225f009944ade1a730cbea931236bf4a0f28/scripts/debugger/debugger.jl#L53).

The core JSON RPC implementation on the Julia side we have is [here](https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/jsonrpcendpoint.jl), and I think that is pretty robust. In particular, it should handle scenarios like when you are in a function that processes a request, and then want to send another request to the client, before you have finished handling the original request.

So I think what I'll do next is add a callback style API a la what you have in Atom to the JSON RPC implementation we have in LS, that is something I had wanted to do for a long time already. I think once we have that we have everything we need on the Julia side, and then we can try to use that for the REPL communcation, right?

Random other thought: I would not introduce any globals in the implementation, a la the global connection in the Atom code, just because I think we might have situations in the future where one process communicates with multiple other end points.
