### ISSUE TITLE
Display modes for inline execution

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1228]
Currently inline execution writes the code that's evaluated into the REPL and displays the result.
With https://github.com/julia-vscode/julia-vscode/pull/1222 we can have a basic inline display as well.

So imho we should have config options for:
1. Show Result in Editor.
2. Show Result in REPL.
2.1 Show Executed code in REPL.

Does that make sense to everyone?

**Comment by aviatesk** [comment]
sounds fine to me, Juno doesn't have a config equivalent to `2.1`, but having that will make the feature more compatible with the current julia-vscodo extension's behaviour.

**Comment by davidanthoff** [comment]
Yes, that sounds right to me.

I think an important question is whether we should show results in the editor by default or not, i.e. what default config value we pick there.

I'm tending towards off, mainly because I think it is nice if the extension broadly behaves like most other VS Code language extensions. I guess another aspect is whether we think of this inline display stuff as something we want to point users to, or whether we think of it mainly as making sure Juno users don't have to completely use a feature? I think my own preference right now would be that we actually try to steer folks towards notebooks for interactive work that shows results inline, and see this feature mostly as a bridge implementation for Juno users? But in any case, happy to hear others, we should obviously make this decision jointly!
