### ISSUE TITLE
Bring Juno Plus to VSCode

### ISSUE THREAD

**Issue by aminya** [julia-vscode/julia-vscode#1242]
https://github.com/aminya/juno-plus

# Toolbar

VSCode already has a small place for adding buttons. We can probably use the same thing to bring juno-plus to VSCode.

![image](https://user-images.githubusercontent.com/16418197/82874659-e4279280-9efb-11ea-9610-ed8dc65bb3fb.png)

If it was not easy to use that toolbar we can add a floating pane (fake toolbar).

![image](https://user-images.githubusercontent.com/16418197/82874708-f9042600-9efb-11ea-872c-5665f55a63c5.png)

I also made some dropdowns for Atom's toolbar. If we bring it to VSCode, we can use it to group a bunch of buttons together and save some space. 

https://github.com/suda/tool-bar/issues/297#issuecomment-614409447
![dropdown2](https://user-images.githubusercontent.com/16418197/79500505-1cc97780-7ff2-11ea-8fcd-ada1b17b84bf.gif)

# Snippets
Snippets are already there! 
https://github.com/aminya/juno-plus/tree/master/snippets_converted/vscode

We can enhance them by using VSCode's features. https://github.com/aminya/juno-plus/issues/3

**Comment by davidanthoff** [comment]
I think in general that the Julia extension should not add much UI, and if we do it should be in the spirit of the VS Code UI story. And toolbars for example are not really part of the VS Code UI design. So maybe something like toolbars could be hosted in a different extension that depends on the Julia extension and essentially extends the base extension by adding additional UI elements?

For the other things: probably best to open individual issues for individual features you think we might want to add to the extension, so that we can discuss them one-by-one?
