### ISSUE TITLE
Changing REPL mode along with executeJuliaCodeInREPL

### ISSUE THREAD

**Issue by tshort** [julia-vscode/julia-vscode#141]
I've got a Julia package that implements a custom REPL [here](https://github.com/tshort/OpenDSSDirect.jl). That REPL is for scripts in another language. It's a "sticky" REPL mode. I just wrote a VSCode mode for that [here](https://marketplace.visualstudio.com/items?itemName=tshort.language-opendss).     

I'd like to be able to use `Ctrl-Enter` to submit my other-language script to the custom REPL mode in Julia. I'm part-way there. I added a command and keystroke to directly use `language-julia.executeJuliaCodeInREPL` from my other-language script. It works great if I'm in the proper REPL mode in the Julia terminal. It's not so great if I'm in the wrong REPL mode. I'd like to be able to tell Julia to switch to the right REPL mode before the code is sent. Is there a way to do that or pointers to explore?

It looks like more REPL modes will become sticky (https://github.com/JuliaLang/julia/issues/19202), so this might be important for other uses.

P.S. julia-vscode is awesome!

**Comment by ZacLN** [comment]
Hmm, I'm not sure what can be done here using the default VScode terminal API for sending code.

As a not particularly elegant solution could you leave the Julia terminal in the standard REPL mode and have your `language-julia.executeJuliaCodeInREPL` command in `opendss-vscode` wrap the text in a `evalasdss(text_from_vscode)` before sending it to the terminal?

**Comment by tshort** [comment]
That approach should work. As you say, it's not particularly elegant. And, if the VSCode terminal is already in the alternate REPL mode, it'll mess up the opposite way.

**Comment by davidanthoff** [comment]
Right now we just send the plain text from the editor to the julia terminal window, and with that setup I don't think we can handle that.

I would very much like to eventually change that, actually, so that the julia REPL process has a background task that "listens" on a socket for messages from the IDE, and then any code to be executed is sent to that background task and run there. That would enable all sorts of cool things (e.g. execution in the context of a module, transmission of line numbers etc.). The core problem there is that we would need an API that this background task can use that controls the REPL, for example hides it and shows it etc. (#105). I tried to understand the REPL code, but it is one of those pieces of code that are probably really clever, but essentially incomprehensible for anyone except the original author, and there is no documentation... So I'll put this issue on the backlog for now, maybe someone will have a good idea at some point.

**Comment by tshort** [comment]
I've also given up on this. The VSCode terminal doesn't expose much of an API. I was hoping I could just send characters to the terminal to switch modes, but there's no way that I can find to check any status from the terminal. I couldn't even find how to grab the active terminal.

On the Julia side, I got stuck the same place David and others have run into in #105.

**Comment by davidanthoff** [comment]
We now have various code execution modes that should work even if one is in a different REPL mode, so I'm going to close this issue.
