### ISSUE TITLE
v0.16.x. Language server crashes 5 times and does not get restarted

### ISSUE THREAD

**Issue by ozmaden** [julia-vscode/julia-vscode#1422]
After upgrading the extension to v.16.x my language server keeps crashing. See the screenshot provided below.

![julia](https://user-images.githubusercontent.com/33359548/85989279-9ae1cb80-b9f0-11ea-86c9-92d4b74c16ec.PNG)

The REPL and the Julia Workspace seem to work fine. This language server behavior is not seen in the previous versions v.15.x. Therefore I have rolled back.

My system:
- Windows 10
- Julia 1.4.1
- Extension v0.16.11 (behavior same with the v0.16.7)
- VS Code v1.46.1

 The crash reports are set to send automatically. Glad to provide extra information if needed. Any help is appreciated.

**Comment by rlrs** [comment]
Is there an easy way to downgrade the extension? I can't find the 0.15.x vsix anywhere, and the 0.16.x version barely works for me.

**Comment by pfitzseb** [comment]
You can right click the Julia extension in the marketplace and select "Install another version".

Did you enable crash reporting for the extension? That drastically increases the chance we can fix this.

**Comment by rlrs** [comment]
Ah, I had the VSCodium version installed, so there apparently weren't any older versions. 
I've run it in VSCode with 0.16.11 and crash reporting enabled, but the issue seems to be something else, since it unfortunately it also seems to crash for me on older versions such as 0.15.x and 0.14.x, starting 5 Julia processes sitting at 100% cpu.
