### ISSUE TITLE
Show "Compiled Mode" toggle in debug toolbar

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1506]

**Comment by davidanthoff** [comment]
I'm still hoping that we'll get a version of JuliaInterpreter at some point that doesn't need this at all...

Moving this to the toolbar would be a bit more involved, I think, because we would need to add custom messages to the DAP to handle all of this? The current implementation is very simple because we can hook into the whole breakpoint settings story of the DAP.

**Comment by pfitzseb** [comment]
Yeah, this definitely isn't trivial to implement. Let's hope we make some progress on the debugger during JuliaCon :)

**Comment by lewisl** [comment]
Uh, how do you get compiled mode by any other means?

**Comment by pfitzseb** [comment]
In the breakpoint section: 
![grafik](https://user-images.githubusercontent.com/6735977/88829882-80586900-d1cd-11ea-9e8d-3df79a68e6f5.png)

**Comment by lewisl** [comment]
Read the announcement mail. Thanks for posting.

This is all pretty terrific.

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/julia-vscode/julia-vscode/pull/1888.

**Comment by pfitzseb** [comment]
This now lives in the
