### ISSUE TITLE
Replacement for Juno.profiler()?

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1545]
The way it did coloring and all of that was great.

**Comment by SebastianM-C** [comment]
There is `@profview`, but it doesn't color lines of code like in Juno. It shows some timings inline, but I'm not sure exactly what they mean.

**Comment by pfitzseb** [comment]
Yup. For now we're hoping that upstream will take care of the UI issues for us :)

**Comment by davidanthoff** [comment]
I think the most useful thing here would be to open specific issues upstream at https://github.com/microsoft/vscode-js-debug, beyond that I don't think there is anything actionable for us here, right?

**Comment by ajkeith** [comment]
VS Code is looking great! As far as I can tell, these issues haven't been opened upstream yet, is that right? From what I can tell, the three things the Juno profiler had that are missing in vs code are

1. Line highlighting: using variable-length line highlighting in the editor to show the percentage of calls made by that line 
2. Flamegraph clicking: clicking a box in the profile-view flamegraph takes you to the corresponding line in the editor
3. Flamegraph coloring: coloring the flamegraph by arbitrary variables instead of time (i.e., gc and dynamic dispatch for julia)

If that captures the difference in functionality, I can open feature request issues at https://github.com/microsoft/vscode-js-debug for them.

**Comment by pfitzseb** [comment]
The right upstream repo for this is https://github.com/microsoft/vscode-js-profile-visualizer and we've already opened a few issues there :)

**Comment by ajkeith** [comment]
Are there any workarounds for line highlighting that don't depend on upstream changes? For example, would it be possible do full length highlighting where the alpha or hue represent the percentage of calls made by each line (instead of length)? e.g., lines with more calls would be a darker red but highlighted all the way across.

**Comment by lrnv** [comment]
Would just like to say that the 'stock' visualisations from vscode, although it makes sense to use them, are quite un-usable compared to what we had in Juno. 

It also seems like the upstream repo does not move a lot... Could we just 'plot' the ProfileView.jl output as a workaround ? Maybe an html version of it, there were some in the past.

**Comment by marius311** [comment]
Just to highlight in case you didn't know (it took me way too long using the VSCode profiler to realize) but you can get a nearly identical flamegraph to Juno's by clicking on the little hidden "flame" icon then on the equally hidden "toggle left heavy view". Its still not the inline visualizations which I agree were awesome, but its something.

**Comment by lrnv** [comment]
Yes this is what I use, but if the stack is too deep, it's buggy... And no way to get a meaningfull coloring, which was also very important info ! A centralized way to run @code_warntype all over the stack at once..
