### ISSUE TITLE
Soft scope for inline evaluation?

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1556]
Should inline evaluation use soft-scope rules? Maybe only when running code in `Main`?

Current behaviour for inline evaluation:
![image](https://user-images.githubusercontent.com/6735977/89201513-e1a78000-d5b1-11ea-9d1e-25c20140c66a.png)
For REPL evaluation (because we use `include_string` for that as well):
![image](https://user-images.githubusercontent.com/6735977/89201592-04399900-d5b2-11ea-8b7c-189292280e2f.png)

**Comment by jlperla** [comment]
Maybe see if wrapping in https://github.com/stevengj/SoftGlobalScope.jl calls does what you need without much work?

**Comment by jlperla** [comment]
Also, what about running a script? Isn't consistency with that also important?

**Comment by pfitzseb** [comment]
AFAICT we're using hard-scoping *everywhere* in VSCode atm.

**Comment by jlperla** [comment]
I see. So even the shift-enter to the REPL is using hardscope. Then the issue is consistency with the 1.5 repl rather than internal consistency.

One option to consider, which maintains the consistency I like, is to have a toggle with "usesoftscope" which just always passes things through the macro if it is on. It would make the REPL consistent with the 1.5 repl. It would also make the rest of code in vscode consistent with the REPL (basically an IJulia compatible mode)...

But there are many downsides, of course. Although I would always use the option personally.

**Comment by jlperla** [comment]
@davidanthoff @pfitzseb I am walking away from this now that I have brought it up.

 I don't see any obvious answers here, but having the vscode repl different from the base repl doesn't smell right.

 maybe @stevengj has some thoughts since he championed this with the REPL and patched IJulia. I am sure the broader perspective on where this stuff goes next...

**Comment by stevengj** [comment]
See also #540.   Especially now that this is the default in the Julia REPL, I feel like it should be the default for the terminal and other interactive contexts as well.

**Comment by jlperla** [comment]
I agree completely. And to me, doing "run script" in a gui is an interactive context. So having an opt-out "usesoftscope" option which applies to absolutely everything would make lots of sense
