### ISSUE TITLE
Allow `# %%` as cell separator

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1566]
On VScode 1.47.3 and Julia 1.0.2, the following file gives UndefVarError, demonstrating that “Julia: Execute Code Cell and Move” is not functioning properly:

```julia 
# %%
2+2
# put your cursor here and press shift-enter

# %%
x + 2
```

**Comment by pfitzseb** [comment]
There's onyl one cell there after our standards :) Only `##` works as the delimiter right now.

**Comment by tbenst** [comment]
Ah okay, thanks. Can I make this a feature request then? `# %%` is supported by both [Juno](http://docs.junolab.org/v0.6/man/basic_usage.html#Cell-Evaluation-1) and [VSCode Python](https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells). Might also be nice to document this, perhaps even on README as code cell is fundamental IMHO.

Thanks for this great package :).

**Comment by pfitzseb** [comment]
We made the explicit choice to only support `##` and not allow this to be user-configurable. I am somewhat sympathetic to the prior-art-argument though.

**Comment by aviatesk** [comment]
yeah, I feel I want to recover `# %%` as the cell delimiter because I'm so used to it. 
And I think the consistency with the other packages that provides similar functionality would be great (I also might like to point [hydrogen](https://github.com/nteract/hydrogen), which supports in-editor inline execution like ours, uses `# %%` as the cell delimiter)
I don't think this needs to be configurable though.

Any thought on this, @davidanthoff ?

**Comment by davidanthoff** [comment]
I'm indifferent :)

**Comment by aviatesk** [comment]
okay, let's support both separators then.

**Comment by aviatesk** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1575

**Comment by tbenst** [comment]
Wow, thanks for the rapid decision and implementation! Amazing to see how fast this project is moving
