### ISSUE TITLE
Linting not working in julia 1.5?

### ISSUE THREAD

**Issue by atbug** [julia-vscode/julia-vscode#1572]
![image](https://user-images.githubusercontent.com/8522036/89361928-8c936900-d69a-11ea-88e4-79cc05258853.png)

I don't have a package called `HackableText`, `foo` and `b` are not defined. It seems the only mistake that julia-vscode picks up is wrong signature of `setindex!`.

**Comment by aviatesk** [comment]
This is because we have turned off our missing refs report by default from the last release because of FPs:
![image](https://user-images.githubusercontent.com/40514306/89362558-23970a00-d709-11ea-8f6b-7cbc4990266c.png)

You can recover the functionality by turning it into `all` or `symbols` by yourself. We may turn it on again once we get satisfied with our environment handling.
