### ISSUE TITLE
Running "Run julia file" with the following code, causes a crash

### ISSUE THREAD

**Issue by RaananHadar** [julia-vscode/julia-vscode#1599]
This causes a crash when pressing the play button with the following code:
```
using Plots

# plot some data
plot([cumsum(rand(500) .- 0.5), cumsum(rand(500) .- 0.5)])
```

produces the following in my terminal:
```
 Warning: Some Julia code in the VS Code extension crashed with
│   e = Endpoint is not running, the current state is closed.
└ @ VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-1.0.3/scripts/error_handler.jl:5
```
Using Julia 1.5.0 on ubuntu 18.04 with julia extension v1.0.3 for vscode.

**Comment by mkitti** [comment]
@RaananHadar is trying to execute this script non-interactively and he previously reported on Slack that it works fine using the REPL.

There are several issues:
1. There is no command to show the plot.
2. The program is immediately exiting.

Here is some minimum code to get this work:

```julia
using Plots

# plot some data
plot([cumsum(rand(500) .- 0.5), cumsum(rand(500) .- 0.5)],show=true)  # show the plot immediately
readline() # wait for the user to press enter in the terminal window before exiting
```

@RaananHadar also mentioned the desire for a more MATLAB-like workflow. I recommend reviewing the workflow recommendations here:
https://docs.julialang.org/en/v1/manual/workflow-tips/

We can then create a "script" TestPlot.jl as follows:
```julia
module TestPlot

using Plots

export make_my_plot

function make_my_plot()
    # plot some data
    plt = plot([cumsum(rand(500) .- 0.5), cumsum(rand(500) .- 0.5)])
    display(plt)

    if(!isinteractive())
        print("Press enter to exit:")
        readline()
    end
end

function __init__()
    make_my_plot()
end

end
```

Start the Julia REPL is VSCode:
1. Press Ctrl-Shift-P and search for julia REPL
2.
```julia
julia> push!(LOAD_PATH,pwd())
4-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
 "/home/mkitti/julia"

julia> using TestPlot
[ Info: Precompiling TestPlot [top-level]

julia> make_my_plot()
```

Due to Revise.jl, changes to the `make_my_plot()` function will be automatically updated in the REPL. Use *Ctrl-Enter* to execute the current line of code or highlighted code in the REPL.

The reason for all of this is to
A) Avoid global variables which will slow down Julia code because of the difficulty of compiling it. By putting code into a function right away, it is easier to compile.
B) Only incur the compiling latency of Plots and other packages a single time due to the persistent Julia REPL session. (You don't restart the MATLAB REPL from scratch every single time, do you?)
C) Make use of Revise.jl's automatic code loading. See the Revise.jl documentation: https://timholy.github.io/Revise.jl/stable/

As for plotting in general, I recommend exploring the various Plot.jl backends:
https://docs.juliaplots.org/latest/backends/

I would also look into Gaston.jl for fast plotting and Makie.jl for GPU accelerated graphics. For interactivity, look into Plotly(JS), PyPlot, InspectDR.

**Comment by RaananHadar** [comment]
Due to your feedback, I can get the plot to show.

Ultimately... there is still something crashing though in the vscode extension. And since alot of users coming from matlab will probably try to run something similar (my code [came from here](https://juliabyexample.helpmanual.io/#Plots)), this will confuse the user into thinking that their attempt to display the plot, caused the extension to crash. So I think the issue should still stay open.

**Comment by mkitti** [comment]
I actually do not think anything is really crashing. The program you wrote just executed and exited rather abruptly. I should say here that when I do run your code, I get the same error message.

However, when I add a `sleep(1)` command I no longer have this issue.

```julia
using Plots

# plot some data
plot([cumsum(rand(500) .- 0.5), cumsum(rand(500) .- 0.5)],show=true)

sleep(1)
```

If I were to ask the julia-vscode developers to do something here it would be to consider another term for "crashed" here:
1. https://github.com/julia-vscode/julia-vscode/blob/master/scripts/error_handler.jl#L5
2. Make the play button configurable to "Julia: Execute file" which will run the file within the running Julia REPL. That is in contrast to "Run Julia File" which you did that cold boots Julia.

**Comment by RaananHadar** [comment]
I completely agree with you. The term "crashed" is misleading and confusing to the user. The issue is that it should be changed.

**Comment by mkitti** [comment]
1. I recommend focusing this issue on modifying https://github.com/julia-vscode/julia-vscode/blob/master/scripts/error_handler.jl#L5 to use alternate verbage for this kind of error.

2. There is discussion of "Julia: Execute file" over at #1478 . Let's focus discussion on that topic there.

**Comment by davidanthoff** [comment]
The original issue strikes me as a bug: there shouldn't be an error message in that scenario.

**Comment by professorderekdecker** [comment]
My 2020 MacBook Air (M1 chip) freezes (even the spinning rainbow ball stops spinning) when I press the green (full screen) button on the plot window. I can't launch Force Quit (Command-Option-Esc) and have to hold down the power button to restart my Mac. Up until then, the interactive plot window is interactive and can be moved. How do I prevent the plot window buttons from crashing my computer?

Newbie

julia code:

# Tutorial 02x10: GLMakie Interactive

# Julia v1.5.3

#=
    Package used in this tutorial:
        GLMakie v0.1.30
=#

# Makie.jl Citation: https://doi.org/10.5281/zenodo.4450294

################################################################################

################################################################################
# Observables
################################################################################

using GLMakie

################################################################################
# Sliders
################################################################################

# initialize plot

fig = Figure(resolution = (3840, 2160))

# add axis

ax1 = fig[1, 1] = Axis(fig,
    # borders
    aspect = 1, targetlimits = BBox(-10, 10, -10, 10),
    # title
    title = "Sliders Tutorial",
    titlegap = 48, titlesize = 60,
    # x-axis
    xautolimitmargin = (0, 0), xgridwidth = 2, xticklabelsize = 36,
    xticks = LinearTicks(20), xticksize = 18,
    # y-axis
    yautolimitmargin = (0, 0), ygridwidth = 2, yticklabelpad = 14,
    yticklabelsize = 36, yticks = LinearTicks(20), yticksize = 18
)

# darken axes

vlines!(ax1, [0], linewidth = 2)
hlines!(ax1, [0], linewidth = 2)

# create sliders

lsgrid = labelslidergrid!(fig,
    ["slope", "y-intercept"],
    Ref(LinRange(-10:0.01:10));
    formats = [x -> "$(round(x, digits = 2))"],
    labelkw = Dict([(:textsize, 30)]),
    sliderkw = Dict([(:linewidth, 24)]),
    valuekw = Dict([(:textsize, 30)])
)

# set starting position for slope

set_close_to!(lsgrid.sliders[1], 1.0)

# layout sliders

sl_sublayout = GridLayout(height = 150)
fig[2, 1] = sl_sublayout
fig[2, 1] = lsgrid.layout

# create listener

slope = lsgrid.sliders[1].value

intercept = lsgrid.sliders[2].value

x = -10:0.01:10

y = @lift($slope .* x .+ $intercept)

# add line plot

line1 = lines!(ax1, x, y, color = :blue, linewidth = 5)

# reset axes limits, if necessary

xlims!(ax1, -10, 10)
ylims!(ax1, -10, 10)

# add scatter plot

rx = -10:0.5:10
ry = rand(length(rx)) .+ -rx * 0.5 .+ 3
scatter1 = scatter!(ax1, rx, ry, color = :red, markersize = 15)

# reset axes limits, if necessary

xlims!(ax1, -10, 10)
ylims!(ax1, -10, 10)

**Comment by mkitti** [comment]
@professorderekdecker could you open a new issue so that we can address your specific example separately?
