### ISSUE TITLE
Send code to REPL mode only

### ISSUE THREAD

**Issue by juliohm** [julia-vscode/julia-vscode#1643]
Whenever we are in package mode and press CTRL+ENTER, the code is sent to the package manager, which is undesired. I wonder if it would be possible to always switch to REPL mode before sending the code.

**Comment by davidanthoff** [comment]
One of the many reasons why Alt+Enter is better :)

Ctrl+Enter just copy-pastes, so there is little we can do about that. But we will eventually move everything over to the Alt+Enter model.

I'll close this because we are already tracking that we eventually want to deprecate the whole copy-paste story.
