### ISSUE TITLE
Autocomplete for non-built-in packages?

### ISSUE THREAD

**Issue by ShuhuaGao** [julia-vscode/julia-vscode#1885]
It seems that VS code Julia seldom autocompletes for third-party packages installed via `add`. Let's take the well-known `Flux` package for an example.

1. After `using Flux`, it does not recognize the `Flux` module and no autocompletion appears.
 
![Snipaste_2021-01-25_11-48-57](https://user-images.githubusercontent.com/20141984/105659839-afddf900-5f04-11eb-8dab-30338140184c.png)

2. `Flux` has a member `ADAGrad` but still not autocompletion.
![Snipaste_2021-01-25_12-06-02](https://user-images.githubusercontent.com/20141984/105660339-c173d080-5f05-11eb-8bb1-16bacec301f9.png)

However, note that the REPL autocompletion works for the above two cases. That is, after inputting ` Flux.ADAG` in REPL, a Tab key autocompletes `Flux.ADAGrad`.

Is there any way to improve the IntelliSense of VS code julia?

Version:
- Julia 1.5.3
- VS Code 1.52.1
- Julia extension 1.0.10

**Comment by pfitzseb** [comment]
We should give you completions by default if Flux is in your environment and loadable. Please check the lower left for the `Julia env: ...` entry and set that accordingly.

**Comment by ShuhuaGao** [comment]
Thanks. You are right. I need to choose the proper Julia environment and then wait for the Julia extension to finish indexing packages. After that, IntelliSense works.

**Comment by camilogarciabotero** [comment]
Hi @ShuhuaGao 

This issue is happening to me, but the solution posted do not solve it. I'm running a Mac Pro 2020 `x86_64-apple-darwin18.7.0` 

- Julia 1.5.3
- VS Code 1.54.1
- Julia extension 1.1.34

If any more information is needed I'll be looking forward to share.
Thanks, for your work and time.
Camilo

**Comment by ShuhuaGao** [comment]
Hi, @camilogarciabotero. On Windows and Ubuntu, the VS code Julia works automatically.

For example, when you start working with Julia, the status bar should display `Indexing a package` like the figure below (if it has not done yet).
![image](https://user-images.githubusercontent.com/20141984/110895560-f95b9980-8334-11eb-993a-16e7cb260e9a.png)

Once the indexing finishes, auto-completion appears.
![image](https://user-images.githubusercontent.com/20141984/110896372-66bbfa00-8336-11eb-8e2d-7fda67a531b1.png)

Make sure that your environment and language mode are right.

![image](https://user-images.githubusercontent.com/20141984/110896443-9834c580-8336-11eb-808a-989a74751887.png)

**Comment by camilogarciabotero** [comment]
Hi @ShuhuaGao,

Thanks for your quick reply. I tried the workflow several times, yet no autocompletion after importing the packages... `Base` and `Core` packages work great for autocompletion though.

I updated Julia and the Julia-vscode extension to the last release:

For what is worth, here I left some info about my set up.

```
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 6
```

I also installed Julia via Hombrew.

Thank you for your help.
Camilo.

**Comment by behinger** [comment]
same issue on Ubuntu 22 with newest vscode and julia extension

**Comment by gdalle** [comment]
Same issue here on macOS

**Comment by HorizonP** [comment]
Version:
- julia 1.9.2
- Ubuntu 22.04 LTS (vscode remotely connected)
- vscode-julia 1.47.2

Same issue happened for me after upgrading Julia 1.8 to 1.9
I figured out it could be the symbol server cache incompatibility problem or maybe the cache is broken. Re-install the vscode-julia extension doesn't help because it never wipe up the symbol server cache at `~/.vscode-server/data/User/globalStorage/julialang.language-julia`. Once I have manually deleted this folder and allow the extension to re-build cache, it finally works for non-built-in packages

**Comment by Lauel09** [comment]
> Same issue here on macOS with everything up to date.
> 
> Could we reopen this issue?

I had the same issue, of autocompte not working on non-built-in package for example like CSV, or DataFrames.
I hope this might help:-
1. Ensure you open the exact folder your project is in, for example instead of opening `~/Documents/proj/` try to open `~/Documents/proj/linear_regression', because if you do the former, the environment wouldn't detect the folder.
This is what was happening with me:-
![image](https://github.com/julia-vscode/julia-vscode/assets/19989996/2d6597c5-2799-430a-9d45-9957f463deac)

As you can see the autocomplete doesn't work:-
![image](https://github.com/julia-vscode/julia-vscode/assets/19989996/ba6dbabe-ee66-488a-9fa9-8f6a902f439d)

After changing the folder, either the `env` would be detected automatically or, you can click on the bottom left again:
![image](https://github.com/julia-vscode/julia-vscode/assets/19989996/1d3b5664-91da-4da6-bfd5-1389cc580062)

Pick the right environment, and voila:
![image](https://github.com/julia-vscode/julia-vscode/assets/19989996/0e183ccb-6d01-4c3d-bddc-d55790390356)

I hope it helps.
Lauel
