### ISSUE TITLE
Release latest?

### ISSUE THREAD

**Issue by PallHaraldsson** [julia-vscode/julia-vscode#1949]
I noticed:

v1.0.10 Latest
on Nov 13, 2020

here at Github (to the right).

All 1.1.x versions are marked "prerelease", but shouldn't the latest (or some 1.1.x) be marked as "latest", since I saw the 1.1. announcement on Discourse?

I'm not sure if this controls anything (for this or any Julia package), it just makes the code look older than it is.

**Comment by davidanthoff** [comment]
I pushed a commit to `master` that might do this: https://github.com/julia-vscode/julia-vscode/commit/68e7271da9ec7c6e91f645c438e2005f78c08d84. I didn't go via a PR because we need to have this on `master` to test in any case. And we'll have to wait until we tag a new release to see whether it actually works.

**Comment by davidanthoff** [comment]
Alright, our automatic azure pipeline story now automatically does this when we release a version to the release channel marketplace.
