### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2017]
Is it ok to start using github actions?
We can use just GitHub actions just for tests to start with, and leave existing release process in Azure Pipelines.
Happy to keep using Azure Pipelines as well

**Comment by davidanthoff** [comment]
So one major problem with our Azure Pipelines is that they've become very slow because we are running all the tests in all the Julia packages on all Julia versions and all platforms that we support. It is a crazy test matrix :) I think I want to definitely keep that for our release pipeline, but I think we actually should try to get a much faster set of CI tests that we run on PRs routinely, that test the core extension, rather than the underlying Julia packages. From my end, I think it would actually make a lot of sense to start using GitHub Actions for that.

@pfitzseb and @ZacLN, any thoughts on this?
