### ISSUE TITLE
Tracking what's required to get Notebook Support

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2043]
I wanted to work on getting variable view (the same one you have in repl) working with notebooks, but not sure how we track these things.

Not sure how this repo manages features and the like.
Labels, Zenhub, Github projets, etc.

Basically I'm trying to find a way to:
* Track all issues/features/bugs, etc that are related to notebooks
* Track how far we are in getting there?
* What are the goals, milestones (e.g. V1 - get xyz, V2 - variables and the like, V3 - debugging)

For instance if the goal is to have some part of Notebooks done, I'd like to see how far we are from completing it and what's left.

FYI - we don't need to change/invent processes just because of these questions of mine.
We can also just create a giant list of items in an issue and GitHub does an awesome job at letting us know how many are completed, and the like (hence no need to use zenhub/projects or the like).

**Comment by davidanthoff** [comment]
So we don't have a super sophisticated process :)

I would suggest that we use the label `area-notebook` to track all issues related to the notebook implementation. I just gave you Triage access to this repo so that you can start to apply labels yourself.

We currently don't have much of a medium or longterm planning, primarily because we are all volunteers and we've operated on "whoever wants to work on something can, and when that is done, it will ship". So essentially everything lands on the `Backlog` milestone, and then if there is a PR that could be merged, we assign it to the `Next Patch` or `Next Minor` milestone to schedule it... I think what might make sense for the notebook story is that we add a GitHub Project with columns vor v1, v2 and v3? And then we can just move the issues/PRs that have the `area-notebook` label in these columns to designate what we are thinking about timing for these? That whole thing would then just be independent from the scheduling we are doing for the general extension, i.e. that project would essentially just give a sense on what is happening on the `notebook` branch? Not sure this is a great idea, but don't have a better one right now :)

**Comment by davidanthoff** [comment]
So something like https://github.com/orgs/julia-vscode/projects/6 ?

**Comment by DonJayamanne** [comment]
Lets try projects, it it doens't get used, then lets kill it, i don't want to introduce a process that unnecessarily complicates things just because of one individual.

Thanks for replying with the details. As we work on notebooks, i'll add more issues so we & others know what's remaining to make it awesome.
Closing this issue, thanks again
