### ISSUE TITLE
Support launching a kernelspec

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2048]
I know some Jupyter users create/update kernelspec with custom environment variables in the kernelspec.json.
I believe this is possible in Julia kernelspec as well.

I don't see any support for launching such kernels.
Basically all we need to do is  inject these env variables into the kennel process that's being launched.
And allowing the user to select such kernels in the kernel pickers as well.

**Comment by davidanthoff** [comment]
So I think my preference would be to completely ignore the kernelspec story, mainly because I would really like that everything works without any setup/install steps, and if we rely on kernelspec files we would have to somehow install them.

My thinking was that we could add configuration options in the extension itself that for example allow a user to add additional env variables into the kernel process.
