### ISSUE TITLE
Getting started and installing dependencies

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2049]
How is a user supposed to start with Julia notebooks in vscode today? Who installs the dependencies?

To my knowledge having Julia isn't sufficient.
The ijulia package needs to be installed, or is this something the extension ships with and then somehow available (via the cli arts) in the kernel process that is launched?

Fyi, I'm still learning how Julia works.

**Comment by davidanthoff** [comment]
So I think we can easily achieve a solution where a user needs to install Julia, VS Code and the two extensions and nothing else and everything will work! That is actually one of my main goals with all of this :)

So we _don't_ need IJulia.jl and we don't need any extra installation of any dependencies. We ship all the Julia code that is needed to make this work inside the extension itself and then load that into the Julia client process that is our kernel.

The first three lines [here](https://github.com/julia-vscode/julia-vscode/blob/334a1334189f1dfe28d77c14b879b4ac59cc0e5b/scripts/notebook/notebook.jl#L1) run at the very beginning of the kernel startup, and they modify the package loading environment, so that we can load the `VSCodeServer` package from within the extension, and not from the normal file system locations where users install packages. And then once we have loaded that, we restore the normal package loading env, so that if a user later tries to load a package from a notebook, it will just load normally from the standard locations.

Another way to look at this is that the `VSCodeServer` package that we ship with the extension just has all the same functionality that IJulia.jl provides, it just uses a different comm protocol (our own home grown thing that works via JSONRPC) rather than ZMQ and the standard Jupyter messages.

This is generally one of the main design goals of the extension: we never, ever want to have a situation where something only works if a user has installed some package or something like that, we always want to ship everything we need as part of the extension, and then it should work without any install step. That has worked really well over the last couple of years, we have _very_ few (if any) problems re dependencies ever :)

**Comment by DonJayamanne** [comment]
> So we don't need IJulia.jl and we don't need any extra installation of any dependencies. We ship all the Julia code that is needed to make this work inside the extension itself and then load that into the Julia client process that is our kernel.

Oh yes forgot that we have our own kernel, oops, totally forgot. Still think about Jupyter world..
