### ISSUE TITLE
sysimage creation issue

### ISSUE THREAD

**Issue by drhouse82** [julia-vscode/julia-vscode#2202]
Hi,
I cannot manage to create and use a custom sys image.
I'm on current Windows 10, VSCode Julia extension 1.22, Julia 1.61.

- I open a new folder in VSCode
- I open a REPL
- I do `] activate .` and `] add CairoMakie`
- I select the environment in the status-bar of VsCode as current environment
- I create a single .jl script 
```
using CairoMakie
fig = Figure() 
ax = Axis(fig)
lines([1,2,3],[5,3,2])
display(fig)
```
- excecuting the file takes 48s.
- I run "julia: Build custom sysimage for current environment". That takes 4 min and produces a dll file in the folder. No real success message in the end. Output:
```
[ Info: Now building a custom sysimage for the environment 'd:\Dropbox\Documents\Julia\image_test'.
[ Info: PackageCompiler: creating system image object file, this might take a while...

Terminal will be reused by tasks, press any key to close it.
``` 
- in the extension settings I have enabled "use an existing custom sysimage when starting a REPL".
- I have restarted VSCode.
- Upon opening a REPL, I see no message or anything... looks like always.
- excecuting the above file still takes ~37s. (started after REPLS is responsive, language server and indexing is finished).
- Interestingly, if I cannot delete the dll while VSCode is running... So there must be some interaction.

So... Actually I'm not sure what happens. I have been expecting something in the <3s range... Is this the anticipated outcome? Can I see somewhere if the image is loaded? Is it a peculiarity of Makie?

**Comment by davidanthoff** [comment]
Have you timed the initial `using CairoMakie`? I would expect that to be much faster. But for the other calls, it might still be the case that those methods aren't compiled into the sysimage. I am not sure at the moment whether PackageCompiler.jl uses a precompile.jl file if it is present in a package to identify which methods to compile or not...

I'm going to close the issue here, because at the end of the day we are just providing a thin layer on top of PackageCompiler.jl, so any improvement for this would need to happen in PackageCompiler.jl.

**Comment by drhouse82** [comment]
You're right, thank you.
`using CairoMakie` is <1s vs. ~10s before.
