### ISSUE TITLE
F2 for renaming doesn't pick-up exclamation marks of the current name

### ISSUE THREAD

**Issue by rapus95** [julia-vscode/julia-vscode#2249]
when using f2 on a function name that has a trailing `!` the prefilled text doesn't show that exclamation mark.

**Comment by AbdulrhmnGhanem** [comment]
This isn't a problem with the Julia language server; the rename request is made with the correct function name to the language server. Also, it isn't a problem with the grammar because the token is detected as shown below.

![image](https://user-images.githubusercontent.com/37152329/124578209-4ae0e480-de4e-11eb-9f54-92c39a1bb3d0.png)

#
The same behavior is reproducible with other languages, Rust's macros example is shown below.

![image](https://user-images.githubusercontent.com/37152329/124579545-803a0200-de4f-11eb-9dc4-eb3cf634e186.png)

**Comment by AbdulrhmnGhanem** [comment]
I opened an issue for it in https://github.com/microsoft/vscode/issues/128042.
