### ISSUE TITLE
Stop asking Julia to resolve Julia path

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#2294]
https://github.com/julia-vscode/julia-vscode/blob/5c3d51d4ace5b022c5dd716030eadeb1f2438a43/src/juliaexepath.ts#L142
can be really annoying when the user wants to use e.g. a shell script to start Julia (to set env variables or do other arbitrary things). We should probably be using `which` or `where` directly here.

**Comment by davidanthoff** [comment]
I would actually really like to get to a point where we _don't_ have to resolve the path at all, but can just start everything with a command, so that things like say `julia +1.5` (from `juliaup`) also work. I wanted to look into that soon as well, when I start with the proper `juliaup` integration. Which will make things a lot easier because we won't have to search paths or anything like that anymore, at least on Windows.
