### ISSUE TITLE
Interaction with Gnuplot? No plot window shows.

### ISSUE THREAD

**Issue by PetrKryslUCSD** [julia-vscode/julia-vscode#2321]
The issue is as reported at
https://discourse.julialang.org/t/gnuplot-from-vscode-no-plot/65458

**Comment by wentasah** [comment]
The Gnuplot.jl side of this is discussed at https://github.com/gcalderone/Gnuplot.jl/issues/45. What IMHO remains to solve on vscode side is to at least issue a waning when a REPL command returns something that can only be shown with the Plot Pane enabled. Such a warning would benefit not only the Gnuplot.jl, but also other packages, such as Plots. 

For example, when the Plot Pane is disabled and one runs:
```julia
using Plots
gr()
plot(1:10, rand(10))
```
Nothing happens and the user is confused.

**Comment by pfitzseb** [comment]
> Such a warning would benefit not only the Gnuplot.jl, but also other packages, such as Plots.

That's not what happens with Plots (or at least it's not what's supposed to happen, and doesn't on my machine). If the plot pane is enabled we use, if not, the Base display machinery falls back to Plots' `PlotsDisplay`, which displays the plot in its own window.

**Comment by wentasah** [comment]
Hmm, I looked at this in more detail and `PlotsDisplay` doesn't work on my system (NixOS Linux), because the downloaded binary artifact cannot find the needed libraries (Qt, freetype, ...). This happens in plain text REPL:
```
julia> plot(1:10, rand(10))
env: ‘/home/wsh/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/bin/gksqt’: No such file or directory
connect: Connection refused
GKS: can't connect to GKS socket application

signal (11): Segmentation fault
...
```
This is understandable on NixOS, because Julia is not fully supported there yet. Therefore, I don't think this needs to be treated as a bug and this issue can be closed.

I think it might be good idea to introduce something like `GnuplotDisplay` in Gnuplot.jl. We'll continue the discussion in https://github.com/gcalderone/Gnuplot.jl/issues/45.

**Comment by pfitzseb** [comment]
Ok, I'll close the issue here then.
