### ISSUE TITLE
Highlighting of  `'''`

### ISSUE THREAD

**Issue by ZacLN** [julia-vscode/julia-vscode#246]
`'''` seems to trigger multi line highlighting

**Comment by pfitzseb** [comment]
This happens because the third `'` opens a new char literal scope, as it will for each uneven number of `'`s. It could be argued that we shouldn't allow `'actual linebreak'` as valid (instead of `'\n'`), but the REPL accepts it.

Anyways, this belongs in https://github.com/JuliaEditorSupport/atom-language-julia. :)
