### ISSUE TITLE
Language server keeps crashing

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2553]
1.5.4 crashes every couple hours and fails to restart so I have to restart vscode. How can I debug?

**Comment by dmetivie** [comment]
Since the update to 1.5.4 in my insider VS Code, I got the same issue: the extension kept crashing, and I got an error message similar to [that](https://www.julia-vscode.org/docs/stable/faq/)
`The Language Server failed to precompile.
Please make sure you have permissions to write to the LS depot path at`.
It was all fine the day before. 

Downgrading to 1.5.3 solved the issue for me.

**Comment by pfitzseb** [comment]
Can you paste the actual error message here, @dmetivie? Should be there if you scroll up a bit.

**Comment by dmetivie** [comment]
Here is what I got at the time. 
```The Language Server failed to precompile. 

Please make sure you have permissions to write to the LS depot path at c:\Users\david\AppData\Roaming\Code - Insiders\User\globalStorage\julialang.language-julia\lsdepot\v1 

┌ Error: Some Julia code in the VS Code extension crashed 

└ @ Main c:\Users\david\.vscode-insiders\extensions\julialang.language-julia-1.5.4\scripts\error_handler.jl:15 

ERROR: Failed to precompile LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7] to c:\Users\david\AppData\Roaming\Code - Insiders\User\globalStorage\julialang.language-julia\lsdepot\v1\compiled\v1.6\LanguageServer\jl_E82A.tmp. 

Stacktrace: [1] top-level scope @ c:\Users\david\.vscode-insiders\extensions\julialang.language-julia-1.5.4\scripts\languageserver\main.jl:69 [Info - 11:58:04] Connection to server got closed. Server will restart.

 [ Info: Starting the Julia Language Server 
```
I hope it helps.
I have just tried to re obtain the error message by updating to 1.5.4, but it seems to work without issues.

**Comment by jtrakk** [comment]
Where can I look for debug info?
