### ISSUE TITLE
VSCode linter not able to reason about the 1.7 destructuring syntax properly

### ISSUE THREAD

**Issue by MrVPlusOne** [julia-vscode/julia-vscode#2639]
A minimal example to demonstrate this:

For the following code
```julia
struct TestStruct
    a
    b
end

struct TestWrapper
    s::TestStruct
end

# linter generates "missing references" for s.b
function test(wrapper::TestWrapper)
    (; s) = wrapper
    s.b
end

# but works fine if not using the destructuring syntax
function test_2(wrapper::TestWrapper)
    s = wrapper.s
    s.b
end
```

The linter has the following behavior:
![image](https://user-images.githubusercontent.com/11240361/146685214-48136ccc-ba65-48fb-b799-7bc135abbeea.png)

**Comment by HugoMelchers** [comment]
Just replying to this issue to say that I'm running into this as well right now. Based on the suggestions that the language server is providing, it thinks that the type of `s` is `TestWrapper` instead of `TestStruct`.
![suggestion1](https://user-images.githubusercontent.com/22659200/200646153-109d9a5e-a4c5-4620-a524-22b55a7d6816.png)
The warnings at `s.b` doesn't show up here for some reason, but in more complicated code I do get equivalent warnings.
![suggestion2](https://user-images.githubusercontent.com/22659200/200646162-7204019c-0fb2-455c-93df-835679a41295.png)
