### ISSUE TITLE
underlining `Possible method call error.Julia(IncorrectCallArgs)` not interacting well with @chain

### ISSUE THREAD

**Issue by akdienes** [julia-vscode/julia-vscode#3042]
using the @chain macro from Chain.jl, the lines inside the chain, e.g. `groupby(:MyCol)` have blue squiggled underlines with the above warning. This would be very helpful if it were not inside @chain, but maybe there is some way to make the two packages interact more nicely

**Comment by cocoa1231** [comment]
Seems to be happening to me with `plot`. The code works correctly without errors but VSCode complains this. I am using VSCodium though.

![image](https://user-images.githubusercontent.com/12653684/193419901-e2901c4c-fe63-4e75-a3b7-f9c322ba7da2.png)

**Comment by davidanthoff** [comment]
I don't think we can do much about this, in general macros are hard for the linter...

**Comment by einarpersson** [comment]
@davidanthoff 

But surely this cannot be the end of it?

(As someone who is really struggling to "get along with Julia" I would say that Julias tooling and these kind of (perhaps minor) annoyances are piling up and creating resistance. I understand that I might sound spoiled, but I guess I'm kind of used to being spoiled using other languages 😇 )

But OK, since I don't want errors or warnings sprinkled around my code - I have the option to either stop using this vscode extension (of course not) or stop using `@chain` everywhere I use it today. I guess the latter is possible, but it would be quite a big refactoring since it's used everywhere. 

![image](https://user-images.githubusercontent.com/6043691/205037991-831302ba-1690-486b-9a85-6ee0c9b177ab.png)

In my case above the call error happens in `groupby` but not `select`, `transform`, `combine` ... Any idea why? Is there anything the DataFrame contributors could do? Or `@chain`?

Another reflection: If it is the case that "in general macros are hard for the linter..." (which I completely trust, you know a lot more than me) - isn't the reasonable follow up question - how can the tooling be adopted to this reality? Could there be an option to turn off warnings for certain errors (with high specificity) for example? And/or some kind of guidelines for macros to be friendlier for linting?

**Comment by yummy527** [comment]
I have the same issue with DataFrames' function, such as semijoin.

**Comment by pfitzseb** [comment]
You can disable the `julia.lint.call` setting for now to get rid of these warnings.
Medium term we probably want to disable the linter completely for macros.
