### ISSUE TITLE
Language Server looks up all files added to workspace

### ISSUE THREAD

**Issue by alex180500** [julia-vscode/julia-vscode#3155]
Hello, I installed julia with juliaup from the windows store (win 11), then installed Julia 1.8.2. Everything works fine in the Julia shell.
I installed the vscode julia extension and made a very simple print program.
I was trying to use the VS Code REPL feature but it takes **~2/3 min** to start each time getting stuck in the LanguageServer startup.
```julia
  Activating project at `c:\Users\aless\.vscode\extensions\julialang.language-julia-1.38.2\scripts\environments\languageserver\v1.8`
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at 'c:\Users\aless\AppData\Roaming\Code\User\globalStorage\julialang.language-julia\symbolstorev5'.
[ Info: Starting LS at 1668364752
[ Info: Received new data from Julia Symbol Server.
```
The `Starting LS at 1668364752` takes the most time.
I don't have any package yet, everything is clean.
Another thing is that VS Code opens the REPL immediately and I can use it by writing in it while waiting these 2-3 min but if I do **ctrl+enter on the lines they are not sent to the REPL until the server has started**.
After that the REPL is activated and everything is fast.
Thank you in advance!

**Comment by alex180500** [comment]
Still have this problem, the lines are not sent to REPL unless the server has started

**Comment by bnarum** [comment]
I had a similar (the same?) issue. My setup had some different repos in a workspace and one folder (added as "Add Folder to Workspace...") containing a lot of data. It seems the language server searches through the data folder, which reasonably takes a lot of time. When I removed the data folder from the workspace, I could start executing code relatively fast again (< 30 seconds). Otherwise, it took 3-5 minutes.

There should be an option to exclude certain folders from being searched by LanguageServer. Is there such an option? I'd like to still have data folders available in the workspace but the startup time becomes too long.

**Comment by alex180500** [comment]
Yes it is the same problem.
In my opinion the Language Server should only look up at opened files.

**Comment by alex180500** [comment]
Any update?

**Comment by alex180500** [comment]
I'd say there are no news on this.

**Comment by pfitzseb** [comment]
The next release of the extension will have a more detailed timing breakdown and might bring some performance improvements.
