### ISSUE TITLE
Quarto Incompatibility

### ISSUE THREAD

**Issue by ParadaCarleton** [julia-vscode/julia-vscode#3250]
Currently, Julia-vscode seems to have some kind of issues with the VSCode Quarto extension (the language-neutral successor to RMarkdown for scientific notebooks). Specifically, LaTeX insertions seem not to be working; typing `\lam` correctly suggests autocompleting to `\lambda=λ` in a Julia file, but not in Quarto.

**Comment by davidanthoff** [comment]
We don't have support for quarto files in our extension, so probably more useful to open this issue over in some quarto repo.

**Comment by ParadaCarleton** [comment]
> We don't have support for quarto files in our extension, so probably more useful to open this issue over in some quarto repo.

Well you see, I asked there, and they told me to ask here :sweat_smile: in general the problem seems to be caused by the language server crashing whenever Quarto is open. cc @jjallaire

**Comment by jjallaire** [comment]
@ParadaCarleton If there is a crash, the best thing you can do is gather up a stack trace and post it here. Better than that would be running the Julia extension in a debugger and trying to diagnose what is causing the crash. It's likely that the cause is straightforward and in that case should be an easy fix

**Comment by davidanthoff** [comment]
I think I'm not even understanding why our language server would be active for quarto files at all? We don't understand that syntax, we don't register our LS for these files, so wouldn't we (the Julia extension) just be completely out of the picture?

**Comment by ParadaCarleton** [comment]
> I think I'm not even understanding why our language server would be active for quarto files at all? We don't understand that syntax, we don't register our LS for these files, so wouldn't we (the Julia extension) just be completely out of the picture?

I'm as confused as you are. I have no idea how Quarto implements multi-language support. All I know is that sometimes, latex like `\ge + tab` in Julia blocks autocompletes correctly, but mostly it doesn't. And also the Julia language server crashes a lot while I'm using Quarto. I _think_ the times where autocomplete was successful is when the language server wasn't crashed. @jjallaire

**Comment by jjallaire** [comment]
The Quarto extension implements completion, hover, signature tips, go to definition, and formatting by invoking LSP commands explicitly from the VS Code Extension API (https://code.visualstudio.com/api/references/commands). Since Quarto `.qmd` files are a hybrid format (they can have multiple languages), a virtual document in the target language is created and provided as the `uri` argument to the command (this is typically a temp file in the same directory as the target `.qmd`). This works for HTML, CSS, JS, Python, R, Julia, and LaTeX.

It looks like some recent change in the Julia extension may have caused this to stop working (at least in some cases) as we know of many users successfully using Julia with the Quarto VS Code extension over the past year or so since the extension was released.

Another entry point we use to the Julia extension is for running cells. For this we use the API exported from here: https://github.com/julia-vscode/julia-vscode/blob/main/src/extension.ts#L155 (although based on my reading of this issue that API is not in play here).

**Comment by ParadaCarleton** [comment]
> It looks like some recent change in the Julia extension may have caused this to stop working (at least in some cases) as we know of many users successfully using Julia with the Quarto VS Code extension over the past year or so since the extension was released.

I actually just noticed this has been going on for [a while](https://discourse.julialang.org/t/unstable-julia-language-server-was-quarto-vscode-and-unicode-characters/90317).
