### ISSUE TITLE
Make the Debug Adapter Protocol implementation client agnostic

### ISSUE THREAD

**Issue by igorlfs** [julia-vscode/julia-vscode#3413]
Hello!

Thanks for making this great tool! I know it's a _vscode_ extension, but I was wondering how hard would it be to make the DAP logic uncoupled from vscode (or maybe create a wrapper, so it can be used outside vscode?). I'm not really the first person to bring up, it has been [raised](https://github.com/julia-vscode/DebugAdapter.jl/issues/59) on the adapter repo as well, and there's plenty of discussion within [vim](https://github.com/puremourning/vimspector/issues/256), [emacs](https://github.com/emacs-lsp/dap-mode/issues/173) and [neovim](https://github.com/mfussenegger/nvim-dap/issues/532) communities. Most notably, there's a suggestion to launch the debugger in a terminal using the `runInTerminal` request, instead of using vscode directly (see [here](https://github.com/puremourning/vimspector/issues/256#issuecomment-695794837)).

I'm only raising this issue here in hopes of getting more visibility, as it seems more actively maintained than the adapter's repo (and definitely some changes to the extension itself would be required for making it work).

**Comment by jclsn** [comment]
I would +1 this as a heavy Vim user who is currently starting to like Julia a lot

**Comment by davidanthoff** [comment]
The biggest problem is probably that we don't have a Julia implementation of the actual DAP, instead we implement the DA as an "inline" version as part of the extension and then use JSON-RPC for the communication between the extension and the Julia process. The JSON-RPC messages we send are _very_ similar to what the DAP defines, but of course use a different wire protocol and aren't compliant with any spec.

So really the first thing that would need to happen for this to work is that someone would need to create a package similar to JSONRPC.jl that implements the equivalent DAP parts. Or maybe we could create something where there is a common base package for JSONRPC.jl and a future DAP.jl that implements the generic messaging API, but not a specific wire transport format, or something like that.

If that existed it would probably be feasible to change DebugAdapater.jl to actually implement the DAP, and then switch the extension in VS Code from this inline debug adapter into one that uses the DAP instead.

All of this would be _a lot_ of work, and I don't have plans to tackle that at the moment. I am doubtful that will change anytime soon because I am also just not entirely sure that the current method of using JuliaInterpreter.jl will ever deliver the kind of smooth debugging experience that we _really_ want, and so I'm not sure I want to invest more time into that. My current idea was primarily to hope that at some point the Julia core team will tackle debugging properly, and then see on what strategy that might be based and at that point revisit the debugging integration into the extension.

**Comment by davidanthoff** [comment]
Oh, another option that would make all of this much easier is if https://github.com/microsoft/debug-adapter-protocol/issues/226 were to happen. At that point our existing DebugAdapter.jl would probably only require very small changes to be a full implementation of the DAP.

**Comment by jclsn** [comment]
Seems unlikely as it is a 7 year-old issue, but I poked them

**Comment by pfitzseb** [comment]
FWIW, I recently got a bit annoyed at the additional complexity in our integration. Refactoring DebugAdapter.jl to support the actual protocol doesn't sound too hard tbh. At the same time it would also be super cool to separate the protocol layer and the implementation a bit more, so that you wouldn't _need_ to use JuliaInterpreter as the backend.

But as David says: The main constraint here is developer time, which neither of us have much to spare, especially since this is only relevant for a fairly small user base.

**Comment by davidanthoff** [comment]
Yeah, there is no question that the current implementation is less than ideal. I've wanted to add debugging support to notebooks and tests, and I think that would all be simpler/easier if we just used DAP to communicate between the extension and the Julia process... Might be worth taking another look at the actual DAP messaging format (not the specific messages, really just the core message structure) and see how different/similar it is to JSON-RPC and then how difficult it would be to factor the transport agnostic parts of JSON-RPC into a common AbstractRPC.jl package, and then JSONRPC.jl and DebugAdapter.jl could add just some minimal transport layer implementation.

There was one other thing where I felt that DAP didn't have the kind of process launch options that we really wanted. I don't really remember the details, but I think there were some things where it would essentially try to launch the debugee in an existing shell or something like that, and that just didn't seem like a good fit for us. The inline debug adapter option allowed me to work around that. But probably worth revisiting and seeing whether that is actually still an issue or not.

If we were to make bigger changes to JSONRPC.jl, we should try to integrate it with https://github.com/davidanthoff/CancellationTokens.jl at the same time, that would also be very useful in general.

**Comment by davidanthoff** [comment]
I just merged a PR that implements the actual DAP over in https://github.com/julia-vscode/DebugAdapter.jl. So per se it should now be possible to use it with any client that implements the DAP. Having said that, the code is fresh and probably still has bugs, but now would actually be a great time for someone to try to integrate it with a different client so that we can iron out any problems.
