### ISSUE TITLE
inline results pushed out of viewport

### ISSUE THREAD

**Issue by marco-meer** [julia-vscode/julia-vscode#3423]
When using word wrap in non-fullscreen Visual Studio Code, parts of the inline results are pushed out of the viewport. This issue makes it difficult to read inline results. It would thus be better to either 
- display inline results under the executed code than on its right side, or
- implement word wrap for inline results, too

**Comment by pfitzseb** [comment]
Not sure what exactly you mean. Can you add a screenshot showing the described behaviour?

**Comment by marco-meer** [comment]
Sorry about that. In this screenshot you can see that the inline result of line 45 is partially hidden, whereas word wrap results in line breaks of the code.
![image](https://github.com/julia-vscode/julia-vscode/assets/99955854/d0ec8afa-36a2-4a7c-88be-20f78e8a41b3)

**Comment by pfitzseb** [comment]
Ah, gotcha. Nothing we can really do about that except for aggressively limiting the length of the inline result previews.

**Comment by marco-meer** [comment]
Thanks for the feedback! Could you tell me where I can find the code relevant for the positioning of the inline result?

**Comment by pfitzseb** [comment]
Somewhere in the VS Code source code. 
We don't have any control over this, except for the (row, col) positioning of the result and some limited css ([ref](https://github.com/julia-vscode/julia-vscode/blob/main/src/interactive/results.ts)).

So we could implement 1), theoretically, but I'm not a big fan of that because it'll cause reflow of the actual document. 2) is not possible, IIRC.

Note that you always have access to the whole result (with wrapping) by hovering over the inline result.

**Comment by marco-meer** [comment]
Yes, whole result by hovering looks nice. thanks again. I'll close this issue.
