### ISSUE TITLE
1.83.2 Fails to connect to language server, LS no output

### ISSUE THREAD

**Issue by ThomJ130** [julia-vscode/julia-vscode#3639]
I repeatedly got errors saying
```
You must have the 'release' channel in Juliaup installed for the best Julia experience in VS Code.
```

Besides already having the most recent release version.

Furthermore, kept getting an error that would say 
```
Error while communicating with the LS. Check Output > Julia Language Server for additional information.
```

However, when looking at VS Codes's output terminal drop-down list, Julia Language Server didn't even show up.

## Solution
The fix was to revert back to 1.79.2.

## What I've Tried
- Uninstall and reinstall Julia extension
- Reclone repo to see if it was an issue there
- Created a new julia project
- Reinstalled julia

**Comment by davidanthoff** [comment]
What do you get when you do `juliaup status`?

**Comment by ThomJ130** [comment]
> What do you get when you do `juliaup status`?

 Default  Channel  Version                   Update
----------------------------------------------------
       *  1.10     1.10.4+0.x64.w64.mingw32

**Comment by davidanthoff** [comment]
The error message says that you need to have the `release` channel installed in Juliaup, which you must have uninstalled at some point. Can you try to reinstall with `juliaup add release`? That should fix it.

**Comment by singularitti** [comment]
Does this mean even if I want to try out the new features with Julia v1.11, I still need to install the release channel? At least on my Mac it works like this. What about the people who don't use Juliaup?

**Comment by davidanthoff** [comment]
The new rules are this: if you have Juliaup installed, you must have the `release` channel installed. Doesn't have to be the default, just needs to be there. For non-Juliaup users you must use Julia 1.6 or newer (soon to be 1.10 or newer once 1.10 is the LTS).

The real change here is that now the only way to use pre 1.6 Julia versions in the REPL etc only works if one uses Juliaup (because then we can use a different Julia version for the language server).

My hope is that all of this is a bit of a transition period, and that we can compile the entire language server with `juliac` once it is more stable and then just ship it as a binary.

**Comment by pfitzseb** [comment]
Can we add a button to that notification to install the release channel?

**Comment by davidanthoff** [comment]
I've also thought about adding a secret `tools` channel to Juliaup that just keeps one version around for us always :)
