### ISSUE TITLE
no easy opt out of telemetry

### ISSUE THREAD

**Issue by gdkrmr** [julia-vscode/julia-vscode#514]
The telemetry dialogue does not provide a button "I do not want to send telemetry", the only thing you can do is to ignore the dialogue, which will pop up at every restart of VSCode, or go to the options and and change the value of `julia.enableTelemetry` to `false`. 
It took me 10 minutes to do figure that out, is annoying and gives a bad impression about the plugin's respect for user privacy (it is about actions not statements).

And btw, does the plugin send telemetry if you ignore the dialogue?

**Comment by davidanthoff** [comment]
Take a look at our privacy policy: https://github.com/JuliaEditorSupport/julia-vscode/wiki/Privacy-Policy. I do think we are respecting user privacy with the approach we take, i.e. we are never sending anything unless you explicitly opt-in.

**Comment by gdkrmr** [comment]
I really don't doubt that, but having an annoying pop up that has no way of making it go away permanently in an obvious way reminds of "free" android/windows apps that made me switch to open source in the first place.

**Comment by gdkrmr** [comment]
Another way to make things more transparent could be to make the actual data (anonymized of course) or some condensed statistics accessible to everyone, and maybe my own data to me, so I can see where my computer stands performance wise.

This way the user gets an actual feeling on what data is being collected and what for instead of an ominous "we are collecting your data", I am sure very few people actually read the privacy policy. Also data scientists (the Julia target group) will have much more fun with data than with a boring privacy policy ;-)

**Comment by gdkrmr** [comment]
Just for the record, I still think you should provide an opt-out button on that pop-up.

**Comment by MartinOtter** [comment]
vs-code and your extension is really nice, so don't misunderstand me: For our web-site we are currently also struggling with the right balance between getting helpful data and privacy and therefore we had to understand the GDPR regulations that hold since May 2018 in Europe: Usually, the approach is to provide once a default option "no telemetery" and "telemetry" is only switched on if you actively make a click (fulfilled by julia-vscode). The vs-code approach to always ask for "telemetry" at start-up (if "telemetry" is not selected) seems to be on the border. You are of course right that vs-code itself might have a much much larger problem to fulfill the GDPR.

Note, Google got recently a 50 Mill Euro fine (see [article](https://www.cnil.fr/en/cnils-restricted-committee-imposes-financial-penalty-50-million-euros-against-google-llc)) for the ads personalization in Android due to "_... The amount decided, and the publicity of the fine, are justified by the severity of the infringements observed regarding the essential principles of the GDPR: transparency, information and consent._"

**Comment by davidanthoff** [comment]
We never, ever, send anything unless you opt-in explicitly. If you just ignore that notification, we won't send anything. I'm not a lawyer, so I can't tell if that is good enough or not, but I would hope that this is good enough...

**Comment by tribut** [comment]
If you show someone the dialog often enough, they will almost certainly click on any of the buttons by mistake. I agree that nudging your users towards the choice you want them to make is probably fine, but having no UI at all for opting out feel shady.

**Comment by bryevdv** [comment]
There should be an opt-out button.

 I just clicked "yes" because I finally got tired of closing the dialog for the 1000th time. So now I won't be pestered incessantly anymore, but also think you are behaving like jerks to force my hand like this. Is that how you want to be perceived?

**Comment by gdkrmr** [comment]
> I just clicked "yes" because I finally got tired of closing the dialog for the 1000th time.

last time I checked, you could set
```
julia.enableTelemetry = false
```
in the user config.

**Comment by bryevdv** [comment]
Last time I tried to find the info [I was confronted with an empty page](https://www.julia-vscode.org/docs/dev). There should be a button.

**Comment by gdkrmr** [comment]
> the number of complaints we have received is so low relative to the user base

For most people convenience trumps privacy concerns and opting out is only for the more knowledgeable, just as in most parts of the internet.

As this was declared a feature and there is no constructive discussion, I will close the issue.

**Comment by xgdgsc** [comment]
Please set a number, say 10 who added 1 to the top then you will add a button to opt out. Most user would click the other button after they find one that says agree. Low number of people complaining doesn' t mean users are not concerned. This just shows how successfully you cheat people, or just how often it crashes that people would switch to juno to get the work done.

**Comment by pochoi** [comment]
+1 number of complaints
I do not agree with the statement "number of complaints we have received is so low relative to the user base we have" leads to the conclusion that people like this idea.
We need proper controlled experiment (a.k.a A/B testing) to draw such conclusion......

**Comment by MartinOtter** [comment]
Your approach violates GDPR and therefore is against the law in Europe (it is impossible to switch telemetry off once).

Besides that, think about, if all the other Julia package providers would act in the same way as you: No company/organization in the world want that people outside of the company/organization record activities. E.g. All Microsoft telemetry is switched off at my organization (German Aerospace Center).

**Comment by davidanthoff** [comment]
> Your approach violates GDPR and therefore is against the law in Europe (it is impossible to switch telemetry off once).

Hold on: you have to explicitly OPT-IN for the extension to ever send a single bit of telemetry. I don't see how that could possibly be in violation of the GDPR.

> Besides that, think about, if all the other Julia package providers would act in the same way as you: No company/organization in the world want that people outside of the company/organization record activities. E.g. All Microsoft telemetry is switched off at my organization (German Aerospace Center).

Sure, and unless you opt-in we won't send any information, ever. If you want us to stop asking you to opt-in, there is a clear explanation in the privacy policy how you can turn that question off.

**Comment by tribut** [comment]
> Hold on: you have to explicitly OPT-IN for the extension to ever send a single bit of telemetry. I don't see how that could possibly be in violation of the GDPR.

Obviously IANAL, but: The GDPR requires consent to be freely given ([Recital 32](https://gdpr-info.eu/recitals/no-32/)). This implies:

> The element “free” implies a real choice by the data subject. Any element of inappropriate pressure or influence which could affect the outcome of that choice renders the consent invalid.
[Consent](https://gdpr-info.eu/issues/consent/)

Whether the pressure is inappropriate would of course be up to a judge in the end, but I don't think anyone could argue that getting a dialog without a decline button (potentially over and over) creates some pressure to accept.

There's also this:
> It shall be as easy to withdraw as to give consent.
[Art. 7(3)](https://gdpr-info.eu/art-7-gdpr/)

Not saying the pattern is clearly illegal, but the opposite is also not as obvious as you make it sound.

**Comment by davidanthoff** [comment]
I don't think one can interpret a dialog that nicely asks as "inappropriate pressure or influence". The text you cite gives an example of an inappropriate pressure: if an employer asks employees to consent. I think it is entirely clear from what we do that there are literally zero consequences for anyone if someone does not opt-in.

**Comment by cdeil** [comment]
I'm new to Julia and was happy to find your VS code extension. Thank you for that.

But I have to agree 100% with all the complaints above - not offering a "no thanks" option for telemetry in the dialog is shady, putting your wish as a developer for telemetry above what users wants.

Also dismissing the complaints here as low, after already stating that you don't want to change this, isn't friendly. The number of users that find and read a long Github issue discussion will always be tiny for any software in the world. If for you it's really the criterion what users think, you could e.g. make a [Twitter poll](https://help.twitter.com/en/using-twitter/twitter-polls) and ask.

I also developed open-source codes and often times wished we had user telemetry. But I don't understand why you want them so bad - if you gave users the option to easily opt-out, and let's assume 80% do that, then you'll still get the telemetry from the other 20%, as I understand 1000s of users. Why isn't that sufficient to develop the extension?

@davidanthoff - Please re-consider.

**Comment by kkittykait** [comment]
Can I disable this damn annoying popup for telemetry?

Is there another alternative instead of this shit?

**Comment by pfitzseb** [comment]
Yes you can -- there even are instructions on how to do that in the pop up:
![image](https://user-images.githubusercontent.com/6735977/86285589-2ae86680-bbe5-11ea-8926-fc0db1a4842b.png)

See [here](https://github.com/julia-vscode/julia-vscode/wiki/Privacy-Policy#disabling-telemetry) for details.

Also, please mind your tone.

**Comment by kkittykait** [comment]
Already modified the package.json

Shitty and deceptive practice to only have one button

**Comment by davidanthoff** [comment]
I'm not going to allow behavior like the one from @kkittykait on this repo and will block anyone who uses such language and starts to personally attack people.

Happy to receive constructive feedback, but please keep it civil in tone, everyone here is doing this as their hobby and volunteering their time.

**Comment by jonniedie** [comment]
@davidanthoff, thank you for keeping this topic open. I’d like to urge you as strongly as I can to reconsider this.

I’ve recently convinced some of my coworkers to try Julia and, unfortunately, I won’t be able to point them toward VSCode because of this telemetry policy. We have to work with customer proprietary and otherwise sensitive data. If our IT department sees that there is a window that pops up every time you open VSCode until you agree to send telemetry about your code (in which there may be sensitive data), it will lead to a pretty quick ban across our division. The Pkg.jl telemetry issue already raised some flags for people in our group, so there’s already unease about us using Julia. If this were added on top of that, I’m afraid the Julia language itself could even be disallowed for us.

I get that you’re probably only collecting stack traces (or something similar) and not the actual file text, but that won’t matter to anyone’s IT department. It’s much easier to ban things than spend time trying to dive into exactly what’s being collected, especially when there is no easy way to get that information.

Thank you (and everyone else working on it) for making and maintaining this extension. I know that the telemetry data is helpful for catching issues and that making it easy to opt out of will significantly reduce the amount of data you have to work with, but I would still ask you to reconsider.

**Comment by jonniedie** [comment]
Actually, the sentence after the one @bryevdv posted from paragraph 114 of the EDPB Guidelines pretty straightforwardly applies to this case too.

> 114.  ...Where consent is obtained through use of a service-specific user interface (for example, via a website, an app, a log-on account, the interface of an IoT device or by e-mail), ***there is no doubt a data subject must be able to withdraw consent via the same electronic interface, as switching to another interface for the sole reason of withdrawing consent would require undue effort.***

@davidanthoff, @pfitzseb, I don't see how this could possibly be interpreted in a way that doesn't find the julia-vscode extension in violation.

**Comment by stillyslalom** [comment]
Instead of yes/no, how about three options:
* Help the developers improve the Julia extension by automatically submitting anonymized, aggregated usage statistics every [day/week/month]
* Send the following basic information only once (with no implied consent for further data collection)
* Do not send any information

By providing a middle ground, you could satisfy users who want to help out, but are wary of ongoing collection.

**Comment by aplavin** [comment]
> 114. ...Where consent is obtained through use of a service-specific user interface (for example, via a website, an app, a log-on account, the interface of an IoT device or by e-mail), _**there is no doubt a data subject must be able to withdraw consent via the same electronic interface, as switching to another interface for the sole reason of withdrawing consent would require undue effort.**_

I'm not a developer of the plugin nor a layer, but it doesn't look like anything in the current telemetry dialog breaks this rule. Click the button at the bottom ("yes") to consent, or click the button at the top ("X") to withdraw. When starting the extension in e.g. a week one may change his mind, so it makes sense that the dialog pops up again (sometimes).

**Comment by MartinOtter** [comment]
> I'm not a developer of the plugin nor a lawyer, but it doesn't look like anything in the current telemetry dialog breaks this rule. Click the button at the bottom ("yes") to consent, or click the button at the top ("X") to withdraw. When starting the extension in e.g. a week one may change his mind, so it makes sense that the dialog pops up again (sometimes).

If "yes" is selected, the dialog never pops up again. If "X" is selected, the dialog pops up whenever vscode is started. So this is unsymmetrical and against DSGVO.

**Comment by jonniedie** [comment]
@aplavin , this section is about withdrawing consent, which is different than not giving it in the first place. To withdraw consent after you've already given it, you have to go into a JSON file and edit the `"julia.enableTelemetry"` line. This is clearly "switching to another interface".
