### ISSUE TITLE
Failure to access variables exported from user defined module

### ISSUE THREAD

**Issue by PetrKryslUCSD** [julia-vscode/julia-vscode#593]
The hover help works fine for library functions, but it gives me nothing for my own functions (even though I am `using` the module where they are defined).
![image](https://user-images.githubusercontent.com/9855832/48572198-97eaa380-e8bd-11e8-868e-00b87ac9c5fb.png)

This obtains with Julia VS Code Extension, v0.11.0-beta.1

**Comment by ZacLN** [comment]
From the screenshot this looks like MeshExportModule (where I'm assuming `Linearspace` is defined) is not having it's exports handled properly. I assume this is off the master branch of FinEtools? I'll have a look

**Comment by ZacLN** [comment]
Hi I've looked into this a bit more: it's the slightly odd syntax (from my perspective) of importing using the absolute name of the parent modules (rather than `using ..`) in `AlgoDeforLinearModule.jl` that's not being handled correctly. I've got a fix in mind

**Comment by ZacLN** [comment]
As far as I can tell the problems here are due to using the following syntax where you import `ModuleA` explicitly from within `ModuleA`. 
```julia
module ModuleA
module ModuleB
x = 1
end
using ModuleA.ModuleB: x
end
```
This seems to work when used as a package but not from the REPL (where it tries to load `ModuleA` from a package. I'm not quite sure what the solution is here other than to use the more common syntax `using .ModuleB: x` so I'm going to close this for now.
