### ISSUE TITLE
option-enter (alt-enter) fails

### ISSUE THREAD

**Issue by dlfivefifty** [julia-vscode/julia-vscode#676]
I get the following error message when I try to do option-enter: `Execute code block only works once the Julia Language Server is ready.`. I just saw on Slack that someone else has the same issue and wee told that it was due to Julia v1.1 not being supported, but I still get the issue even when I point it to use a Julia v1.0 binary.

**Comment by shhong** [comment]
I'm getting the same error.

**Comment by chelate** [comment]
Me too

**Comment by davidanthoff** [comment]
I think this is because the LS is blocked for a long time initially while it builds up the index... We really should find a better way for all of that...

**Comment by davidanthoff** [comment]
I'm going to move this to the backlog because I don't think we will fix the LS startup issues for v0.12.0.

**Comment by awf** [comment]
Folks, this is still happening -- is it really building an index?   A much better error message would help.  Is there any way in which one can see the indexing status?   There is no mention of "index" anywhere in the extension page in VScode.

**Comment by SyxP** [comment]
To see the indexing status, go to "OUTPUT" in the terminal pane
![Screenshot_2019-12-23_00-07-28](https://user-images.githubusercontent.com/20557013/71324304-5f81b400-2518-11ea-91ab-e040aea9693f.png)

Then select from "Tasks" dropdown "Julia Language Server. If you do not see it may require to Ctrl-Enter/Alt-Enter a few lines to start the Julia extension.

You should see 
![Screenshot_2019-12-23_00-09-59](https://user-images.githubusercontent.com/20557013/71324331-9788f700-2518-11ea-9eba-9be0c9fffff8.png)

It will say "store set" if it indeed has finish running. Otherwise it is building the index.

**Comment by awf** [comment]
I would say this is a dup of https://github.com/julia-vscode/julia-vscode/issues/864

**Comment by tbenst** [comment]
I'm getting this same error (Julia 1.1). My output tab is completely blank. Note that ctrl-enter works fine. lmk how I can help troubleshoot? Will also try julia 1.3 soon...

**Comment by davidanthoff** [comment]
Yes, agreed, this is a dup of #864 and maybe a bit https://github.com/julia-vscode/julia-vscode/issues/1007 as well, so I'm going to close this issue.

@tbenst Alt+Enter only works once the language server is up and running. We know that the startup time for that is not great, but we have other issues that track that already.
