### ISSUE TITLE
linting for macro generated expressions?

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#694]
It seems that the macro deprecate is not recognized correctly, e.g

```julia
@deprecate f(x) sin(x)
```

`f` and `x` will be undefined. 

And similarly, if a function is generated by some custom macro, it will also be undefined.

**Comment by ZacLN** [comment]
Fixed (for `deprecate` at least) here: https://github.com/julia-vscode/StaticLint.jl/blob/master/src/macros.jl#L6.

**Comment by jerlich** [comment]
There is a very similar issue with `@linq df |> where(foo==2)` in [DataFramesMeta](https://github.com/JuliaData/DataFramesMeta.jl)

`where` actually refers to `@where` which is in the `DataFramesMeta` namespace, but this trick of skipping the `@` when using the `@linq` function messes up the linter. I wasn't sure whether to open a new issue, since it seems so similar to this one.

I guess macro's make linting hard.
