### ISSUE TITLE
Starting Julia REPL doesn't work

### ISSUE THREAD

**Issue by PetrKryslUCSD** [julia-vscode/julia-vscode#798]
Downloaded the release candidate 6. Set the Julia executable to
C:\Users\PetrKrysl\AppData\Local\Julia-1.1.1\bin\julia
I get almost 600 "Problems", but the terminal pane remains blank and no prompt appears.

**Comment by davidanthoff** [comment]
Can you try to just not configure a value for the path to julia at all? The extension should automatically find julia if it is installed in a default location (like the one you are using). If you do configure it, you need to add `.exe` to the configured value.

BUT, if problems (in the linter sense) appear, then this might also be some other problem, because I don't think any problems would show up unless the path of the julia executable is configured correctly...

**Comment by PetrKryslUCSD** [comment]
With RC 7 the issue went away.

**Comment by ZacLN** [comment]
Super
