### ISSUE TITLE
start REPL at file path?

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#845]
currently REPL will start at project root path instead of file path, when execute code block/or execute line. This is quite intuitive for things like opening files. The vscode's own file string auto completion will give you an incorrect path in REPL

**Comment by davidanthoff** [comment]
I kind of think that the current behavior is how it should be. If we were to start the REPL in the folder of a file from which you are sending something to the REPL, shouldn't we then also change the working folder if you send something from a file into an already open REPL? And that seems not like a good idea.

Alt+Enter code execution should these days properly handle `@__DIR__` and `@__FILE__`, so I think that is the way to write code that can deal with different working directories.

But, I'm leaving this issue open, happy to convinced otherwise :)
