### ISSUE TITLE
Code navigation doesn't work when there are too many modules in workspaces?

### ISSUE THREAD

**Issue by YongHee-Kim** [julia-vscode/julia-vscode#919]
I've put  `...\.julia\packages\` in VScode to workspace and code navigation doesn't work. (It hangs for some time and the language server crashes) 

Maybe because there are too many modules in the Workspace?

Code navigation works fine. when there are few modules in a workspace. 

![image](https://user-images.githubusercontent.com/7087745/71552852-a2c3b180-2a47-11ea-8f19-f9c09164ad48.png)

**Comment by ZacLN** [comment]
Yep that'll most likely overload the server (for my `packages/` directory this tries to load and link ~20,000 files which quickly eats up all my RAM). 

One way forward could be:
- quickly scan to see how many files are within the workspace folder on loading.
- if its below some level continue as we do now otherwise...
- don't automatically load (to the language server) all files within the workspace. 
- For files that are open in the workspace, use a text based scanner to look for references to the opened file (i.e.  `openedfile.jl`) in all files within the parent directory (and maybe a few levels down). 
- If potential parent files (`parentfile.jl`) are found, load them and run a scopepass (StaticLint) in the hope that we include `openedfile.jl` and add it to the server's files. (If this works we'll have to repeat the process on `parentfile.jl` to ensure we're getting the root of the julia tree.
